// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCDCMessageStmt, err = db.PrepareContext(ctx, addCDCMessage); err != nil {
		return nil, fmt.Errorf("error preparing query AddCDCMessage: %w", err)
	}
	if q.addOutboxMessageStmt, err = db.PrepareContext(ctx, addOutboxMessage); err != nil {
		return nil, fmt.Errorf("error preparing query AddOutboxMessage: %w", err)
	}
	if q.addRoomMemberStmt, err = db.PrepareContext(ctx, addRoomMember); err != nil {
		return nil, fmt.Errorf("error preparing query AddRoomMember: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createRoomStmt, err = db.PrepareContext(ctx, createRoom); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRoom: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteOutboxMessageStmt, err = db.PrepareContext(ctx, deleteOutboxMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOutboxMessage: %w", err)
	}
	if q.getCDCMessagesStmt, err = db.PrepareContext(ctx, getCDCMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetCDCMessages: %w", err)
	}
	if q.getOutboxMessagesStmt, err = db.PrepareContext(ctx, getOutboxMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetOutboxMessages: %w", err)
	}
	if q.getRoomByIDStmt, err = db.PrepareContext(ctx, getRoomByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoomByID: %w", err)
	}
	if q.getRoomByNameStmt, err = db.PrepareContext(ctx, getRoomByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoomByName: %w", err)
	}
	if q.getRoomMembersStmt, err = db.PrepareContext(ctx, getRoomMembers); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoomMembers: %w", err)
	}
	if q.getRoomMessagesStmt, err = db.PrepareContext(ctx, getRoomMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoomMessages: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.incrementRoomVersionStmt, err = db.PrepareContext(ctx, incrementRoomVersion); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementRoomVersion: %w", err)
	}
	if q.listRoomsStmt, err = db.PrepareContext(ctx, listRooms); err != nil {
		return nil, fmt.Errorf("error preparing query ListRooms: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCDCMessageStmt != nil {
		if cerr := q.addCDCMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCDCMessageStmt: %w", cerr)
		}
	}
	if q.addOutboxMessageStmt != nil {
		if cerr := q.addOutboxMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addOutboxMessageStmt: %w", cerr)
		}
	}
	if q.addRoomMemberStmt != nil {
		if cerr := q.addRoomMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addRoomMemberStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createRoomStmt != nil {
		if cerr := q.createRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRoomStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteOutboxMessageStmt != nil {
		if cerr := q.deleteOutboxMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOutboxMessageStmt: %w", cerr)
		}
	}
	if q.getCDCMessagesStmt != nil {
		if cerr := q.getCDCMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCDCMessagesStmt: %w", cerr)
		}
	}
	if q.getOutboxMessagesStmt != nil {
		if cerr := q.getOutboxMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOutboxMessagesStmt: %w", cerr)
		}
	}
	if q.getRoomByIDStmt != nil {
		if cerr := q.getRoomByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoomByIDStmt: %w", cerr)
		}
	}
	if q.getRoomByNameStmt != nil {
		if cerr := q.getRoomByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoomByNameStmt: %w", cerr)
		}
	}
	if q.getRoomMembersStmt != nil {
		if cerr := q.getRoomMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoomMembersStmt: %w", cerr)
		}
	}
	if q.getRoomMessagesStmt != nil {
		if cerr := q.getRoomMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoomMessagesStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.incrementRoomVersionStmt != nil {
		if cerr := q.incrementRoomVersionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementRoomVersionStmt: %w", cerr)
		}
	}
	if q.listRoomsStmt != nil {
		if cerr := q.listRoomsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRoomsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	addCDCMessageStmt        *sql.Stmt
	addOutboxMessageStmt     *sql.Stmt
	addRoomMemberStmt        *sql.Stmt
	createMessageStmt        *sql.Stmt
	createRoomStmt           *sql.Stmt
	createUserStmt           *sql.Stmt
	deleteOutboxMessageStmt  *sql.Stmt
	getCDCMessagesStmt       *sql.Stmt
	getOutboxMessagesStmt    *sql.Stmt
	getRoomByIDStmt          *sql.Stmt
	getRoomByNameStmt        *sql.Stmt
	getRoomMembersStmt       *sql.Stmt
	getRoomMessagesStmt      *sql.Stmt
	getUserByIDStmt          *sql.Stmt
	getUserByUsernameStmt    *sql.Stmt
	incrementRoomVersionStmt *sql.Stmt
	listRoomsStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		addCDCMessageStmt:        q.addCDCMessageStmt,
		addOutboxMessageStmt:     q.addOutboxMessageStmt,
		addRoomMemberStmt:        q.addRoomMemberStmt,
		createMessageStmt:        q.createMessageStmt,
		createRoomStmt:           q.createRoomStmt,
		createUserStmt:           q.createUserStmt,
		deleteOutboxMessageStmt:  q.deleteOutboxMessageStmt,
		getCDCMessagesStmt:       q.getCDCMessagesStmt,
		getOutboxMessagesStmt:    q.getOutboxMessagesStmt,
		getRoomByIDStmt:          q.getRoomByIDStmt,
		getRoomByNameStmt:        q.getRoomByNameStmt,
		getRoomMembersStmt:       q.getRoomMembersStmt,
		getRoomMessagesStmt:      q.getRoomMessagesStmt,
		getUserByIDStmt:          q.getUserByIDStmt,
		getUserByUsernameStmt:    q.getUserByUsernameStmt,
		incrementRoomVersionStmt: q.incrementRoomVersionStmt,
		listRoomsStmt:            q.listRoomsStmt,
	}
}
