// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"encoding/json"
)

type Cdc struct {
	ID        int32           `json:"id"`
	Method    string          `json:"method"`
	Payload   json.RawMessage `json:"payload"`
	Partition int64           `json:"partition"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Message struct {
	ID        int32         `json:"id"`
	RoomID    int32         `json:"room_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Outbox struct {
	ID        int32           `json:"id"`
	Method    string          `json:"method"`
	Payload   json.RawMessage `json:"payload"`
	Partition int64           `json:"partition"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type Room struct {
	ID            int32         `json:"id"`
	Name          string        `json:"name"`
	Version       int64         `json:"version"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	BumpedAt      sql.NullTime  `json:"bumped_at"`
	LastMessageID sql.NullInt32 `json:"last_message_id"`
}

type RoomMember struct {
	ID       int32        `json:"id"`
	RoomID   int32        `json:"room_id"`
	UserID   int32        `json:"user_id"`
	JoinedAt sql.NullTime `json:"joined_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}
