// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	AddCDCMessage(ctx context.Context, arg AddCDCMessageParams) (Cdc, error)
	AddOutboxMessage(ctx context.Context, arg AddOutboxMessageParams) (Outbox, error)
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (RoomMember, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, name string) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOutboxMessage(ctx context.Context, id int32) error
	GetCDCMessages(ctx context.Context, arg GetCDCMessagesParams) ([]Cdc, error)
	GetOutboxMessages(ctx context.Context, arg GetOutboxMessagesParams) ([]Outbox, error)
	GetRoomByID(ctx context.Context, id int32) (Room, error)
	GetRoomByName(ctx context.Context, name string) (Room, error)
	GetRoomMembers(ctx context.Context, roomID int32) ([]User, error)
	GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]GetRoomMessagesRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementRoomVersion(ctx context.Context, id int32) (Room, error)
	ListRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
