// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addCDCMessage = `-- name: AddCDCMessage :one
INSERT INTO cdc (method, payload, partition)
VALUES ($1, $2, $3)
RETURNING id, method, payload, partition, created_at
`

type AddCDCMessageParams struct {
	Method    string          `json:"method"`
	Payload   json.RawMessage `json:"payload"`
	Partition int64           `json:"partition"`
}

func (q *Queries) AddCDCMessage(ctx context.Context, arg AddCDCMessageParams) (Cdc, error) {
	row := q.queryRow(ctx, q.addCDCMessageStmt, addCDCMessage, arg.Method, arg.Payload, arg.Partition)
	var i Cdc
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.Payload,
		&i.Partition,
		&i.CreatedAt,
	)
	return i, err
}

const addOutboxMessage = `-- name: AddOutboxMessage :one
INSERT INTO outbox (method, payload, partition)
VALUES ($1, $2, $3)
RETURNING id, method, payload, partition, created_at
`

type AddOutboxMessageParams struct {
	Method    string          `json:"method"`
	Payload   json.RawMessage `json:"payload"`
	Partition int64           `json:"partition"`
}

func (q *Queries) AddOutboxMessage(ctx context.Context, arg AddOutboxMessageParams) (Outbox, error) {
	row := q.queryRow(ctx, q.addOutboxMessageStmt, addOutboxMessage, arg.Method, arg.Payload, arg.Partition)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.Payload,
		&i.Partition,
		&i.CreatedAt,
	)
	return i, err
}

const addRoomMember = `-- name: AddRoomMember :one
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
RETURNING id, room_id, user_id, joined_at
`

type AddRoomMemberParams struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (RoomMember, error) {
	row := q.queryRow(ctx, q.addRoomMemberStmt, addRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.JoinedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, content, created_at
`

type CreateMessageParams struct {
	RoomID  int32         `json:"room_id"`
	UserID  sql.NullInt32 `json:"user_id"`
	Content string        `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage, arg.RoomID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name)
VALUES ($1)
RETURNING id, name, version, created_at, bumped_at, last_message_id
`

func (q *Queries) CreateRoom(ctx context.Context, name string) (Room, error) {
	row := q.queryRow(ctx, q.createRoomStmt, createRoom, name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.BumpedAt,
		&i.LastMessageID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, email)
VALUES ($1, $2, $3)
RETURNING id, username, password, email, created_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Password, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOutboxMessage = `-- name: DeleteOutboxMessage :exec
DELETE FROM outbox
WHERE id = $1
`

func (q *Queries) DeleteOutboxMessage(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteOutboxMessageStmt, deleteOutboxMessage, id)
	return err
}

const getCDCMessages = `-- name: GetCDCMessages :many
SELECT id, method, payload, partition, created_at
FROM cdc
WHERE partition = $1
ORDER BY created_at ASC
LIMIT $2
`

type GetCDCMessagesParams struct {
	Partition int64 `json:"partition"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetCDCMessages(ctx context.Context, arg GetCDCMessagesParams) ([]Cdc, error) {
	rows, err := q.query(ctx, q.getCDCMessagesStmt, getCDCMessages, arg.Partition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cdc{}
	for rows.Next() {
		var i Cdc
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Payload,
			&i.Partition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutboxMessages = `-- name: GetOutboxMessages :many
SELECT id, method, payload, partition, created_at
FROM outbox
WHERE partition = $1
ORDER BY created_at ASC
LIMIT $2
`

type GetOutboxMessagesParams struct {
	Partition int64 `json:"partition"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) GetOutboxMessages(ctx context.Context, arg GetOutboxMessagesParams) ([]Outbox, error) {
	rows, err := q.query(ctx, q.getOutboxMessagesStmt, getOutboxMessages, arg.Partition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Payload,
			&i.Partition,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, version, created_at, bumped_at, last_message_id
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int32) (Room, error) {
	row := q.queryRow(ctx, q.getRoomByIDStmt, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.BumpedAt,
		&i.LastMessageID,
	)
	return i, err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT id, name, version, created_at, bumped_at, last_message_id
FROM rooms
WHERE name = $1
`

func (q *Queries) GetRoomByName(ctx context.Context, name string) (Room, error) {
	row := q.queryRow(ctx, q.getRoomByNameStmt, getRoomByName, name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.BumpedAt,
		&i.LastMessageID,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT u.id, u.username, u.password, u.email, u.created_at
FROM users u
    JOIN room_members rm ON rm.user_id = u.id
WHERE rm.room_id = $1
`

func (q *Queries) GetRoomMembers(ctx context.Context, roomID int32) ([]User, error) {
	rows, err := q.query(ctx, q.getRoomMembersStmt, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT m.id, m.room_id, m.user_id, m.content, m.created_at,
    u.username as author_username
FROM messages m
    LEFT JOIN users u ON m.user_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetRoomMessagesParams struct {
	RoomID int32 `json:"room_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRoomMessagesRow struct {
	ID             int32          `json:"id"`
	RoomID         int32          `json:"room_id"`
	UserID         sql.NullInt32  `json:"user_id"`
	Content        string         `json:"content"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	AuthorUsername sql.NullString `json:"author_username"`
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]GetRoomMessagesRow, error) {
	rows, err := q.query(ctx, q.getRoomMessagesStmt, getRoomMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomMessagesRow{}
	for rows.Next() {
		var i GetRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, email, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, email, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const incrementRoomVersion = `-- name: IncrementRoomVersion :one
UPDATE rooms
SET version = version + 1
WHERE id = $1
RETURNING id, name, version, created_at, bumped_at, last_message_id
`

func (q *Queries) IncrementRoomVersion(ctx context.Context, id int32) (Room, error) {
	row := q.queryRow(ctx, q.incrementRoomVersionStmt, incrementRoomVersion, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.BumpedAt,
		&i.LastMessageID,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, version, created_at, bumped_at, last_message_id
FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.query(ctx, q.listRoomsStmt, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.BumpedAt,
			&i.LastMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
